export const skills = [
  {
    name: "JavaScript",
    years: "6",
    main: true,
    style: "bg-[#F9E79F] border-[#F9E79F]",
  },
  {
    name: "TypeScript",
    years: "5",
    main: true,
    style: "bg-[#B0CFEF] border-[#B0CFEF]",
  },
  {
    name: "Vue.js",
    years: "6",
    main: true,
    style: "bg-[#A8D5BA] border-[#A8D5BA]",
  },
  {
    name: "React.js",
    years: "4",
    main: true,
    style: "bg-[#B3E5FC] border-[#B3E5FC]",
  },
  {
    name: "Python - Django",
    years: "2",
    main: true,
    style: "bg-[#50afff] border-[#50afff]",
  },
  {
    name: "Angular",
    years: "2",
    main: false,
    style: "bg-[#F8B4B4] border-[#F8B4B4]",
  },
  {
    name: "Redux",
    years: "4",
    main: false,
    style: "bg-[#FCE7B2] border-[#FCE7B2]",
  },
  {
    name: "Nuxt.js",
    years: "4",
    main: true,
    style: "bg-[#B5EAD7] border-[#B5EAD7]",
  },

  {
    name: "Next.js",
    years: "2",
    main: true,
    style: "bg-[#D6D6D6] border-[#D6D6D6]",
  },

  {
    name: "Vuex",
    years: "3",
    main: false,
    style: "bg-[#FAD7A0] border-[#FAD7A0]",
  },
  {
    name: "Pinia",
    years: "5",
    main: false,
    style: "bg-[#DDD6FE] border-[#DDD6FE]",
  },
  {
    name: "Node.js",
    years: "5",
    main: true,
    style: "bg-[#C3E8C3] border-[#C3E8C3]",
  },
  {
    name: "Express.js",
    years: "5",
    main: false,
    style: "bg-[#F9A8A8] border-[#F9A8A8]",
  },
  {
    name: "GraphQL",
    years: "2",
    main: false,
    style: "bg-[#C7C1E7] border-[#C7C1E7]",
  },
  {
    name: "REST",
    years: "5",
    main: true,
    style: "bg-[#EDEDED] border-[#EDEDED]",
  },
  {
    name: "MySQL",
    years: "2",
    main: false,
    style: "bg-[#A7C7E7] border-[#A7C7E7]",
  },
  {
    name: "MongoDB",
    years: "4",
    main: false,
    style: "bg-[#B2DFDB] border-[#B2DFDB]",
  },
  {
    name: "Tailwind CSS",
    years: "5",
    main: true,
    style: "bg-[#A8E6CF] border-[#A8E6CF]",
  },
  {
    name: "Bootstrap 5",
    years: "3",
    main: false,
    style: "bg-[#F9B5B5] border-[#F9B5B5]",
  },
  {
    name: "SASS",
    years: "4",
    main: false,
    style: "bg-[#FCE7B2] border-[#FCE7B2]",
  },
  {
    name: "Bulma CSS",
    years: "3",
    main: true,
    style: "bg-[#C3E8C3] border-[#C3E8C3]",
  },
  {
    name: "AWS Amplify",
    years: "2",
    main: true,
    style: "bg-[#FAD7A0] border-[#FAD7A0]",
  },
  {
    name: "Prismic",
    years: "2",
    main: false,
    style: "bg-[#C7C1E7] border-[#C7C1E7]",
  },
  {
    name: "Cloudinary",
    years: "2",
    main: false,
    style: "bg-[#EDEDED] border-[#EDEDED]",
  },
  {
    name: "Git",
    years: "5",
    main: true,
    style: "bg-[#F8B4B4] border-[#F8B4B4]",
  },
  {
    name: "Jenkins",
    years: "1",
    main: false,
    style: "bg-[#D6D6D6] border-[#D6D6D6]",
  },
  {
    name: "Docker",
    years: "1",
    main: false,
    style: "bg-[#A8D5BA] border-[#A8D5BA]",
  },
  {
    name: "D3",
    years: "2",
    main: false,
    style: "bg-[#F9E79F] border-[#F9E79F]",
  },
  {
    name: "Chart.js",
    years: "2",
    main: false,
    style: "bg-[#B3E5FC] border-[#B3E5FC]",
  },
  {
    name: "Vite",
    years: "5",
    main: true,
    style: "bg-[#DDD6FE] border-[#DDD6FE]",
  },
  {
    name: "Webpack",
    years: "3",
    main: false,
    style: "bg-[#B0CFEF] border-[#B0CFEF]",
  },
  {
    name: "HTML5",
    years: "6",
    main: true,
    style: "bg-[#FFB74D] border-[#FFB74D]",
  },
  {
    name: "CSS3",
    years: "6",
    main: true,
    style: "bg-[#AED6F1] border-[#AED6F1]",
  },
  {
    name: "VS Code",
    years: "6",
    main: false,
    style: "bg-[#007ACC] border-[#007ACC]",
  },
  {
    name: "GitHub",
    years: "6",
    main: true,
    style: "bg-[#E8E8E8] border-[#E8E8E8]",
  },
  {
    name: "Figma",
    years: "1",
    main: false,
    style: "bg-[#A6D1E6] border-[#A6D1E6]",
  },
  {
    name: "Postman",
    years: "4",
    main: false,
    style: "bg-[#FF6C37] border-[#FF6C37]",
  },
  {
    name: "SonarQube",
    years: "1",
    main: false,
    style: "bg-[#F5B7B1] border-[#F5B7B1]",
  },
  {
    name: "JIRA",
    years: "6",
    main: false,
    style: "bg-[#74B9FF] border-[#74B9FF]",
  },
  {
    name: "Performance Optimization",
    years: "6",
    main: true,
    style: "bg-[#F9E79F] border-[#F9E79F]",
  },
  {
    name: "WCAG",
    years: "4",
    main: false,
    style: "bg-[#F8B4B4] border-[#F8B4B4]",
  },
  {
    name: "Responsive Design",
    years: "6",
    main: true,
    style: "bg-[#B3E5FC] border-[#B3E5FC]",
  },
  {
    name: "Agile",
    years: "4",
    main: false,
    style: "bg-[#D6D6D6] border-[#D6D6D6]",
  },
  {
    name: "CI/CD",
    years: "3",
    main: false,
    style: "bg-[#FAD7A0] border-[#FAD7A0]",
  },
  {
    name: "WordPress",
    years: "2",
    main: true,
    style: "bg-[#FBBF24] border-[#FBBF24]",
  },
  {
    name: "Elementor",
    years: "2",
    main: false,
    style: "bg-[#A78BFA] border-[#A78BFA]",
  },
  {
    name: "WooCommerce",
    years: "2",
    main: true,
    style: "bg-[#34D399] border-[#34D399]",
  },
  {
    name: "Yoast SEO",
    years: "2",
    main: false,
    style: "bg-[#F472B6] border-[#F472B6]",
  },
  {
    name: "Contact Form 7",
    years: "2",
    main: false,
    style: "bg-[#60A5FA] border-[#60A5FA]",
  },
  {
    name: "Shopify",
    years: "1",
    main: true,
    style: "bg-[#3B82F6] border-[#3B82F6]",
  },
  {
    name: "Oberlo",
    years: "1",
    main: false,
    style: "bg-[#FBBF24] border-[#FBBF24]",
  },
  {
    name: "Klaviyo",
    years: "1",
    main: false,
    style: "bg-[#F871A1] border-[#F871A1]",
  },
  {
    name: "Bold Upsell",
    years: "1",
    main: false,
    style: "bg-[#D97706] border-[#D97706]",
  },
  {
    name: "Shopify Payments",
    years: "1",
    main: false,
    style: "bg-[#4ADE80] border-[#4ADE80]",
  },
];
